services:
  backend:
    container_name: backend
    image: joaofduraofdamas/phereapi:latest
    ports:
      - 8080:8080
    depends_on:
      - psql
    networks:
      - my-network
    environment:
      - DB_HOST=psql
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}  
      - SPRING_PROFILES_ACTIVE=prod 

  psql:
    container_name: psql
    image: postgres:16.4-alpine3.20
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    networks:
      - my-network

networks:
  my-network: